### ISSUE TITLE
Cjs versions after 3.2 can cause massive memory leaks

### ISSUE THREAD

**Issue by trialism** [linuxmint/cjs#63] opened 2018-01-23 12:26 UTC
This is the related issue on cinnamon: https://github.com/linuxmint/Cinnamon/issues/6850

Downgrading cjs to 3.2.x solves the leaks for many people

**Comment by leigh123linux** [comment] 2018-01-30 13:51
Duplicate of inuxmint/Cinnamon#6850

**Closed** 2018-01-30 13:52 UTC
